"model_name_or_path": "gpt2"
"per_device_train_batch_size": 4
"learning_rate": 2e-4
"num_train_epochs": 10
"data": "KATANABRAVE/stories"
"weight_decay": 0.01
"max_grad_norm": 1
"warmup_steps": 500
"output_dir": "saved_model"
"save_steps": 500
"max_steps": 1000
"local_rank": os.getenv('LOCAL_RANK', 0)